// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1oJ6V4Jt48EAB22o65cP9hg_IrQqZi38',
    appId: '1:26659145227:web:5eb1eeb00102cf2785e90e',
    messagingSenderId: '26659145227',
    projectId: 'fir-learning-b740e',
    authDomain: 'fir-learning-b740e.firebaseapp.com',
    storageBucket: 'fir-learning-b740e.appspot.com',
    measurementId: 'G-F93MC8QKHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMb6Nt8LfcXwXQ9i16Q3axUASUumQ5QNw',
    appId: '1:26659145227:android:59a4bed952f695dd85e90e',
    messagingSenderId: '26659145227',
    projectId: 'fir-learning-b740e',
    storageBucket: 'fir-learning-b740e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAptB2MhzMa5Zv944KptFPOy5_Qx8TlSfI',
    appId: '1:26659145227:ios:90760cd98db66c3285e90e',
    messagingSenderId: '26659145227',
    projectId: 'fir-learning-b740e',
    storageBucket: 'fir-learning-b740e.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAptB2MhzMa5Zv944KptFPOy5_Qx8TlSfI',
    appId: '1:26659145227:ios:90760cd98db66c3285e90e',
    messagingSenderId: '26659145227',
    projectId: 'fir-learning-b740e',
    storageBucket: 'fir-learning-b740e.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1oJ6V4Jt48EAB22o65cP9hg_IrQqZi38',
    appId: '1:26659145227:web:7c4d35622f3258b985e90e',
    messagingSenderId: '26659145227',
    projectId: 'fir-learning-b740e',
    authDomain: 'fir-learning-b740e.firebaseapp.com',
    storageBucket: 'fir-learning-b740e.appspot.com',
    measurementId: 'G-D3VM0YSTLT',
  );
}
